### ISSUE TITLE
[SUGGESTION FOR IMPROVEMENT] Create script to automatically report the grades to the general list of abstract

### ISSUE THREAD

**Issue by slevyrosetti** [jcohenadad/assign-reviewers#4]
The most tedious part of the job is done with the script assign_reviewers.py and that is fantastic!
This is a suggestion to improve further the automatic approach and address the point #6 of the Wiki section "How to use": _"Each reviewer shares their Google Sheet with you, and you can simply copy the reviewer column and append it to the main Google Sheet document. Then, a row-wise summation can easily be done"_

Actually, we don't want to _copy the reviewer column_ into the main spreadsheet as the reviewer's list of submissions is necessarily different from the main spreadsheet and we don't want to do a _row-wise average_ because that would yield the average score across submissions. What we want is to **report the each reviewer's scores in the main spreadsheet at the line corresponding to the rated submissions**, on the right, in the column of the reviewer.

My suggestion is therefore to create a script to be called like:
`report_scores -m main_spreadsheet.csv -s grading_form_Anna.csv grading_form_Elsa.csv`
where:
- `main_spreadsheet.csv` is the main spreadsheet initially generated from the Google form (or a copy of it) which includes all submissions and where the scores will be reported
- `grading_form_NNN.csv` are the csv (or xls) files that were generated by `assign_reviewers` and where the reviewers would have entered their score

And what this script would do is:
1. Add each reviewer's name as a column on the right side in main_spreadsheet.csv
2. For each grading_form_NNN.csv from reviewer NNN, it would report the score of each submission at the corresponding line and column of the reviewer (using the Program Number to find the corresponding line of the submission in the main spreadsheet)

This way, the reviewers won't have to manually find each submission and copy/paste their score in the main spreadsheet ~30 times or more.

Hope this could help!

**Comment by jcohenadad** [comment]
Thank you for the feedback @slevyrosetti ! much appreciated!

> as the reviewer's list of submissions is necessarily different from the main spreadsheet

as can be seen in this image:
![image](https://user-images.githubusercontent.com/2482071/117303563-d50acd80-ae4a-11eb-8c42-a8c8d84addf8.png)

All the rows are kept across raters. Eg: 
- rater1 has to complete lines 0, 2, 4, etc.
- rater2 has to complete lines 1, 3, 5, etc.
- Then, when copy/pasting all the rows from one rater onto the main spreadsheet, it will fill all the completed rows, so we end up with something like this:

|   | rater1 | rater2 | rater3 | average |
|---|--------|--------|--------|---------|
| a | 5      |        | 3      | 4       |
| b | 2      | 3      | 4      | 3       |
| c |        | 2      | 4      | 3       |

Or maybe I misunderstood something?

**Comment by slevyrosetti** [comment]
Alriiight! I totally missed that! My bad, thank you for the clarifications.
I think I have been confused by the first column in the reviewers grading forms which starts at 0 and therefore has a -2 shift compared to the row number of the main spreadsheet.
But then the issue can be closed, my suggestion is not necessary anymore (as long as the number of reviewers stays small enough to manually copy/paste the scores). Thanks again for clarifying that!
